* **Configuration Options**
  
  In this section, all the available configuration is broken down by the key (e.g. ``phlexible_cms``) 
  that defines each possible section of the phlexible bundle configuration.
  
  * :doc:`phlexible_gui </reference/configuration/gui>`
  * :doc:`phlexible_cms </reference/configuration/cms>`
  * :doc:`phlexible_metaset </reference/configuration/metaset>`
  * :doc:`phlexible_mediacache </reference/configuration/mediacache>`
  * :doc:`phlexible_mediamanager </reference/configuration/mediamanager>`

* **Twig**

  * :doc:`Extensions Reference </reference/twig/extensions>`
  * :doc:`Variables Reference </reference/twig/variables>`
