* **Configuration Options**
  
  Ever wondered what configuration options you have available to you in files
  such as ``app/config/config.yml``? In this section, all the available configuration
  is broken down by the key (e.g. ``phlexible_cms``) that defines each possible
  section of your phlexible configuration.
  
  * :doc:`gui </reference/configuration/gui>`
  * :doc:`cms </reference/configuration/cms>`

* :doc:`Twig Extensions </reference/twig/extensions>`

* :doc:`Twig Variables </reference/twig/variables>`
