* :doc:`/cookbook/dashboard/index`
  
  * :doc:`/cookbook/dashboard/portlet`

* :doc:`/cookbook/gui/index`

  * :doc:`/cookbook/gui/scripts`
  * :doc:`/cookbook/gui/css`
  * :doc:`/cookbook/gui/menu`

* :doc:`/cookbook/message/index`

  * :doc:`/cookbook/message/handler`
  * :doc:`/cookbook/message/message`

* :doc:`/cookbook/problem/index`
  
  * :doc:`/cookbook/problem/checker`

* :doc:`/cookbook/search/index`
  
  * :doc:`/cookbook/search/handler`

* :doc:`/cookbook/templating/index`

  * :doc:`/cookbook/templating/links`
  * :doc:`/cookbook/templating/images`
  * :doc:`/cookbook/templating/downloads`
  * :doc:`/cookbook/templating/navigations`
